theme: jekyll-theme-slate
title: DucOps - Revision 1.0
description: Lost in Memory. Forever on a page.

#Socials
linkedin_username: @helloduc

paginate: 5
paginate_path:  "posts/page:num"
plugins: 
  - jekyll-feeds
  - jekyll-paginate
  - jekyll-sitemap

  